# Generated by Django 5.1.1 on 2024-10-18 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacioncurso',
            name='cupo_maximo',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='asignacioncurso',
            name='cupo_ocupado',
            field=models.IntegerField(default=0),
        ),
    ]
