# Generated by Django 5.1.1 on 2024-10-18 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_asignacioncurso_cupo_maximo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='seccion_horario',
        ),
    ]
