# Generated by Django 5.1.1 on 2024-10-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_remove_curso_seccion_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacioncurso',
            name='cupo_maximo',
            field=models.IntegerField(default=0),
        ),
    ]
