# Generated by Django 5.1.1 on 2024-10-18 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_reporte_retroalimentacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='retroalimentacion',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.curso'),
        ),
    ]
