# Generated by Django 5.1.1 on 2024-10-18 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_retroalimentacion_curso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporte',
            old_name='fecha_envio',
            new_name='fecha',
        ),
        migrations.AlterField(
            model_name='reporte',
            name='asunto',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_enviados', to=settings.AUTH_USER_MODEL),
        ),
    ]
