# Generated by Django 5.1.1 on 2024-11-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_rename_fecha_envio_reporte_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='horario',
            field=models.CharField(max_length=100),
        ),
    ]
