# Generated by Django 5.1.1 on 2024-09-15 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='nota',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
